version: '3.8'

# Docker Compose override for E2E testing
# Usage: docker compose -f ../../docker-compose.yml -f docker-compose.test.yml up -d

services:
  # Override API Gateway with test-specific configuration
  api-gateway:
    environment:
      - ENVIRONMENT=e2e
      - NODE_ENV=test
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://betterprompts:betterprompts@postgres:5432/betterprompts_e2e?sslmode=disable
      # Test-specific rate limiting will be applied automatically

  # Override other services if needed for testing
  frontend:
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://localhost/api/v1

  # Keep database and cache with test-friendly settings
  postgres:
    environment:
      - POSTGRES_USER=betterprompts
      - POSTGRES_PASSWORD=betterprompts
      - POSTGRES_DB=betterprompts_e2e

  redis:
    # Use faster cache eviction for tests
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru